/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.modelo.controller.MarcaController;
import br.com.modelo.negocio.Marca;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author anderson_feliciano
 */
public class ListarMarca extends javax.swing.JFrame {
    private MarcaTableModel modelo;
    /**
     * Creates new form ListarMarca
     */
    public ListarMarca() {
        initComponents();
        List<Marca> lista = new ArrayList<Marca>();
        MarcaController mc = new MarcaController();
        lista = mc.getMarca();
        modelo = new MarcaTableModel(lista);
        tbMarca.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMarca = new javax.swing.JTable();
        btInserir = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Marcas");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(61, 41, 60, 18);

        txPesquisa.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPesquisaActionPerformed(evt);
            }
        });
        txPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txPesquisaFocusLost(evt);
            }
        });
        jPanel1.add(txPesquisa);
        txPesquisa.setBounds(60, 70, 420, 30);

        tbMarca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbMarca);
        tbMarca.getColumnModel().getColumn(0).setResizable(false);
        tbMarca.getColumnModel().getColumn(0).setPreferredWidth(10);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 110, 520, 140);

        btInserir.setText("Inserir");
        btInserir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirActionPerformed(evt);
            }
        });
        jPanel1.add(btInserir);
        btInserir.setBounds(60, 290, 70, 50);

        btAtualizar.setText("Atualizar");
        btAtualizar.setBorder(null);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btAtualizar);
        btAtualizar.setBounds(150, 290, 70, 50);

        btExcluir.setText("Excluir");
        btExcluir.setBorder(null);
        jPanel1.add(btExcluir);
        btExcluir.setBounds(240, 290, 70, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPesquisaActionPerformed
        MarcaController mc = new MarcaController();
        List<Marca> lista = new ArrayList<Marca>();
        lista = mc.buscarMarcaByNome(txPesquisa.getText());
        modelo.limpar();
        modelo = new MarcaTableModel(lista);
        tbMarca.setModel(modelo);
        
        
    }//GEN-LAST:event_txPesquisaActionPerformed

    private void txPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPesquisaFocusLost

    }//GEN-LAST:event_txPesquisaFocusLost

    private void btInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirActionPerformed
        InserirMarcaGUI im = new InserirMarcaGUI(modelo);
        im.setVisible(true);
        
    }//GEN-LAST:event_btInserirActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        int selecionado = -1;
        selecionado = tbMarca.getSelectedRow();
        
        if(selecionado >=0){
            Integer idMarca = (Integer)modelo.getValueAt(selecionado, 0);
        
        AtualizarMarcaGUI at = new AtualizarMarcaGUI(selecionado, idMarca, modelo);
        at.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Selecionar uma linha");
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbMarca;
    private javax.swing.JTextField txPesquisa;
    // End of variables declaration//GEN-END:variables
}
